AWSTemplateFormatVersion: '2010-09-09'
Description: 'Bedrock Support Assistant - Complete infrastructure with VPC'

Parameters:
  AllowedCIDR:
    Type: String
    Description: CIDR block allowed to access the application
    Default: 0.0.0.0/0

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: BedrockSupportVPC

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: BedrockSupportIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: BedrockSupportPublicSubnet

  # Route Table
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: BedrockSupportPublicRT

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  # Security Group
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: !Ref AllowedCIDR
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref AllowedCIDR
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BedrockSupportSG

  # IAM Role
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: BedrockInvokePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: '*'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      IamInstanceProfile: !Ref InstanceProfile
      ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Redirect all output to log file
          exec > >(tee /var/log/user-data.log)
          exec 2>&1

          echo "Starting Bedrock Support Assistant setup..."
          
          # Install Python and dependencies
          echo "Installing Python..."
          dnf install -y python3 python3-pip
          
          # Configuration
          REGION="eu-west-2"
          MODEL_ID="amazon.nova-pro-v1:0"
          PORT=8080
          
          # Create application directory
          mkdir -p /opt/bedrock-app
          cd /opt/bedrock-app
          
          # Create requirements.txt
          cat > requirements.txt << 'EOF'
          boto3>=1.34.0
          watchtower>=3.0.0
          EOF
          
          # Install Python packages
          echo "Installing Python packages..."
          pip3 install -r requirements.txt
          
          # Create application
          cat > app.py << 'EOFPY'
          #!/usr/bin/env python3
          import json
          import logging
          import sys
          import os
          import traceback
          from datetime import datetime
          from http.server import HTTPServer, BaseHTTPRequestHandler
          
          import boto3
          from botocore.exceptions import BotoCoreError, ClientError
          
          # Configuration from environment or defaults
          REGION = os.environ.get("AWS_REGION", "eu-west-2")
          MODEL_ID = os.environ.get("MODEL_ID", "amazon.nova-pro-v1:0")
          MAX_TICKET_LENGTH = 5000
          PORT = int(os.environ.get("PORT", "8080"))
          
          # Setup logging
          log_dir = os.path.expanduser("~/bedrock-app-logs")
          os.makedirs(log_dir, exist_ok=True)
          log_file = os.path.join(log_dir, "app.log")
          
          logging.basicConfig(
              level=logging.INFO,
              format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
              handlers=[
                  logging.FileHandler(log_file),
                  logging.StreamHandler()
              ]
          )
          
          logger = logging.getLogger(__name__)
          
          # Initialize Bedrock client
          try:
              bedrock_client = boto3.client("bedrock-runtime", region_name=REGION)
              logger.info(f"Bedrock client initialized for region {REGION}")
          except Exception as e:
              logger.error(f"Failed to initialize Bedrock client: {e}")
              bedrock_client = None
          
          # Try to setup CloudWatch logging
          try:
              import watchtower
              cloudwatch_handler = watchtower.CloudWatchLogHandler()
              logger.addHandler(cloudwatch_handler)
              logger.info("CloudWatch logging enabled")
          except Exception as e:
              logger.warning(f"CloudWatch logging setup failed: {e}")
          
          class SupportTicketHandler(BaseHTTPRequestHandler):
              def send_json_response(self, status_code, data):
                  try:
                      self.send_response(status_code)
                      self.send_header("Content-Type", "application/json")
                      self.send_header("Access-Control-Allow-Origin", "*")
                      self.end_headers()
                      self.wfile.write(json.dumps(data).encode("utf-8"))
                  except Exception as e:
                      logger.error(f"Error sending response: {e}")
          
              def do_GET(self):
                  try:
                      if self.path == "/health":
                          logger.info("Health check requested")
                          self.send_json_response(200, {
                              "status": "healthy",
                              "timestamp": datetime.utcnow().isoformat(),
                              "service": "bedrock-support-assistant",
                              "region": REGION,
                              "model": MODEL_ID
                          })
                      else:
                          self.send_json_response(404, {"error": "Not found"})
                  except Exception as e:
                      logger.error(f"Error in do_GET: {e}")
          
              def do_POST(self):
                  try:
                      content_length = int(self.headers.get("Content-Length", 0))
                      if content_length == 0:
                          self.send_json_response(400, {"error": "No content provided"})
                          return
                      
                      body = self.rfile.read(content_length)
                      data = json.loads(body.decode("utf-8"))
                      ticket = data.get("ticket", "").strip()
                      
                      if not ticket:
                          self.send_json_response(400, {"error": "Missing ticket field"})
                          return
                      
                      if not bedrock_client:
                          self.send_json_response(503, {"error": "Bedrock unavailable"})
                          return
                      
                      # Call Bedrock with Nova Pro
                      system_prompt = """Analyze the support ticket and provide JSON with: summary, severity, category, suggested_response"""
                      prompt = f"{system_prompt}\n\nTicket:\n{ticket}"
                      
                      response = bedrock_client.invoke_model(
                          modelId=MODEL_ID,
                          body=json.dumps({
                              "messages": [{"role": "user", "content": [{"text": prompt}]}],
                              "inferenceConfig": {"max_new_tokens": 1024, "temperature": 0.7}
                          })
                      )
                      
                      result = json.loads(response["body"].read())
                      text = result["output"]["message"]["content"][0]["text"]
                      
                      try:
                          analysis = json.loads(text)
                      except:
                          analysis = {"analysis": text}
                      
                      self.send_json_response(200, {"ticket_id": data.get("ticket_id", "N/A"), "analysis": analysis})
                      logger.info("Successfully analyzed ticket")
                      
                  except Exception as e:
                      logger.error(f"Error in do_POST: {e}")
                      logger.error(traceback.format_exc())
                      self.send_json_response(500, {"error": "Internal error"})
              
              def log_message(self, format, *args):
                  logger.info(f"{self.client_address[0]} - {format % args}")
          
          def run_server():
              httpd = HTTPServer(("", PORT), SupportTicketHandler)
              logger.info(f"Bedrock Support Assistant started on port {PORT}")
              logger.info(f"Model: {MODEL_ID}")
              try:
                  httpd.serve_forever()
              except KeyboardInterrupt:
                  logger.info("Shutting down...")
                  httpd.server_close()
          
          if __name__ == "__main__":
              run_server()
          EOFPY
          
          # Set environment variables
          export AWS_REGION=$REGION
          export MODEL_ID=$MODEL_ID
          export PORT=$PORT
          
          # Create systemd service
          cat > /etc/systemd/system/bedrock-app.service << 'EOFSVC'
          [Unit]
          Description=Bedrock Support Assistant
          After=network.target
          
          [Service]
          Type=simple
          User=ec2-user
          WorkingDirectory=/opt/bedrock-app
          Environment="AWS_REGION=eu-west-2"
          Environment="MODEL_ID=amazon.nova-pro-v1:0"
          Environment="PORT=8080"
          ExecStart=/usr/bin/python3 /opt/bedrock-app/app.py
          Restart=always
          RestartSec=10
          
          [Install]
          WantedBy=multi-user.target
          EOFSVC
          
          # Set permissions
          chown -R ec2-user:ec2-user /opt/bedrock-app
          chmod +x /opt/bedrock-app/app.py
          
          # Start service
          echo "Starting Bedrock Support Assistant service..."
          systemctl daemon-reload
          systemctl enable bedrock-app
          systemctl start bedrock-app
          
          echo "Setup complete! Check status: systemctl status bedrock-app"

      Tags:
        - Key: Name
          Value: BedrockSupportInstance

Outputs:
  InstancePublicIP:
    Description: Public IP address of the instance
    Value: !GetAtt EC2Instance.PublicIp
  
  HealthCheckURL:
    Description: Health check endpoint
    Value: !Sub 'http://${EC2Instance.PublicIp}:8080/health'
  
  AnalysisURL:
    Description: Ticket analysis endpoint
    Value: !Sub 'http://${EC2Instance.PublicIp}:8080/'
